/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorDirecciondb;
import ec.edu.ups.modelo.Direccion;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author José Quinde
 */
public class VentanaListarDirecciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaListarPersonas
     */
    public static NuevoModelo modelo;
    public static Set<Direccion> listaDirecciones;
    
    public VentanaListarDirecciones() {
        initComponents();
        modelo = new NuevoModelo();
        Object[] columnas ={"CODIGO","CALLE PRINCIPAL","CALLE SECUNDARIA","NUMERO"};
        modelo.setColumnIdentifiers(columnas);
        tblDirecciones.setModel(modelo);
        llenarTabla();
    }
    /**
     * Llena los datos de la tabla con las direcciones de la base de datos dependiendo su cedula
     */
     public static  void llenarTabla(){
         ControladorDirecciondb controladorDirecciondb=new ControladorDirecciondb();
         String cedula=VentanaListarPersona.cedula;
         listaDirecciones=controladorDirecciondb.listaDirecciones();
         for (Direccion d:listaDirecciones ) {
             if(cedula.equals(d.getCedula_per())){
                Object[] datos = {d.getCodigo(),
                d.getCodigo(),
                d.getCalle_principal(),
                d.getCalle_secundaria(),
                d.getNumero()};
                modelo.addRow(datos);
             }
        }
    }
     /**
      * Metodo para que la tabla no sea editable
      */
      public class NuevoModelo extends DefaultTableModel{
    /**
     * Define la posibilidad de editar las columnas
     */    
    public final boolean [] TblColums= {false,false,false,false};

        @Override
        public boolean isCellEditable(int row, int column) {
            return this.TblColums[column];
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDirecciones = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("LISTAR DIRECCIONES");

        tblDirecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "CALLE PRINCIPAL", "CALLE SECUNDARIA", "NUMERO"
            }
        ));
        jScrollPane1.setViewportView(tblDirecciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDirecciones;
    // End of variables declaration//GEN-END:variables
}
